# Generated by Django 5.2.4 on 2025-07-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('mod', 'Moderator'), ('jr', 'Jury'), ('spec', 'Spectator'), ('def', 'Default')], default='def', max_length=5),
        ),
    ]
