# Generated by Django 5.2.4 on 2025-07-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_action_actionlog_message_actionlog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
